DROP TABLE IF EXISTS BUMON_TBL;
CREATE TABLE team13_shain_tbl(
	SHAIN_ID CHAR(2) NOT NULL,
	SHAIN_NM VARCHAR2(30) NOT NULL,
	SHAIN_ADRESS VARCHAR(30) NOT NULL,
	SHAIN_EMAIL VARCHAR(30) NOT NULL,
	SHAIN_PASS VARCHAR2(30) NOT NULL,
	SHAIN_TELL VARCHAR(20),	
	PRIMARY KEY(SHAIN_ID)
	);

CREATE TABLE team13_shohin_tbl(
	SHOHIN_ID CHAR(5),
	SHOHIN_NM VARCHAR2(30) NOT NULL,
	SHOHIN_PRICE NUMBER(6) NOT NULL,
	SHOHIN_STOCK NUMBER(5) NOT NULL,
	PRIMARY KEY(SHOHIN_ID)
	);
	
CREATE TABLE team13_order_tbl(
	TYUMON_ID INT AUTO_INCREMENT,--(10),
	TYUMON_PRODUCT_ID CHAR(5) NOT NULL,
	TYUMON_KOKYAKU_ID INT NOT NULL,--(5),
	TYUMON_AT DATETIME NOT NULL,
	PRIMARY KEY(TYUMON_ID),
	
	CONSTRAINT fk_order_shohin

        FOREIGN KEY (TYUMON_PRODUCT_ID)

        REFERENCES team13_shohin_tbl(SHOHIN_ID),
        
    CONSTRAINT fk_order_shain

        FOREIGN KEY (TYUMON_KOKYAKU_ID)

        REFERENCES team13_shain_tbl(SHAIN_ID)
);

CREATE TABLE team13_admin_tbl(
	KANRI_ID CHAR(5),
	KANRI_NM VARCHAR(30) NOT NULL,
	KANRI_PASS VARCHAR2(30) NOT NULL,
	PRIMARY KEY(KANRI_ID)
);

CREATE TABLE team13_shiire_tbl(
	SHIIRE_ID CHAR(5),
	SHIIRE_NM VARCHAR2(30) NOT NULL,
	SHIIRE_PRODUCT_ID CHAR(5),
	SHIIRE_ADRESS VARCHAR2(30) NOT NULL,
	SHIIRE_TELL VARCHAR2(20) NOT NULL,
	PRIMARY KEY(SHIIRE_ID),
	
	CONSTRAINT fk_shiire_shohin

        FOREIGN KEY (SHIIRE_PRODUCT_ID)

        REFERENCES team13_shohin_tbl(SHOHIN_ID)
);

CREATE TABLE team13_shiire_history_tbl(
	SHIIRE_HISTORY_ID CHAR(5),
	SHIIRE_KANRI_ID CHAR(5) NOT NULL,
	SHIIRE_MAKER_ID CHAR(5) NOT NULL,
	SHIIRE_NUM NUMBER(5) NOT NULL,
	BOUGHT_AT DATETIME,
	PRIMARY KEY(SHIIRE_HISTORY_ID),
	
	CONSTRAINT fk_shiire_history_admin

        FOREIGN KEY (SHIIRE_KANRI_ID)

        REFERENCES team13_admin_tbl(KANRI_ID),
        
    CONSTRAINT fk_shiire_history_shiire

        FOREIGN KEY (SHIIRE_MAKER_ID)

        REFERENCES team13_shiire_tbl(SHIIRE_ID)
);

CREATE TABLE team13_cart_shohin_table(
	CART_SHOHIN_ID CHAR(5),
	CART_SHOHIN_NM VARCHAR2(30) NOT NULL,
	CART_SHAIN_ID CHAR(5) NOT NULL,
	CART_SHOHIN_NUM NUMBER(5) NOT NULL,
	CART_SHOHIN_PRICE NUMBER(6) NOT NULL,
	PRIMARY KEY(CART_SHOHIN_ID)
);

CREATE TABLE team13_shiharai_tbl(
	SHIHARAI_ID INT,--(2),
	SHIHARAI_NM VARCHAR2(30) NOT NULL,
	PRIMARY KEY(SHIHARAI_ID)
);

CREATE TABLE team13_card_info_tbl(
	CARD_INFO_ID CHAR(5),
	CARD_INFO_NM VARCHAR2(6) NOT NULL,
	CARD_INFO_NUM VARCHAR2(20) NOT NULL,
	CARD_LIMIT_TIME VARCHAR2(6) NOT NULL,
	CARD_USER_ID INT NOT NULL,--(6),
	PRIMARY KEY(CARD_INFO_ID),
	
	CONSTRAINT fk_card_info_shain

        FOREIGN KEY (CARD_USER_ID)

        REFERENCES team13_shain_tbl(SHAIN_ID)
);



