DROP TABLE IF EXISTS BUMON_TBL;
CREATE TABLE team13_shain_tbl(
	SHAIN_ID CHAR(2),
	SHAIN_NM VARCHAR2(30),
	SHAIN_ADRESS VARCHAR(30),
	SHAIN_EMAIL VARCHAR(30),
	SHAIN_TELL VARCHAR(20),	
	PRIMARY KEY(SHAIN_ID)
	);

CREATE TABLE team13_shohin_tbl(
	SHOHIN_ID CHAR(5),
	SHOHIN_NM VARCHAR2(30) NOT NULL,
	SHOHIN_PRICE NUMBER(6) NOT NULL,
	SHOHIN_STOCK NUMBER(5) NOT NULL,
	PRIMARY KEY(SHOHIN_ID)
	);
	
CREATE TABLE team13_order_tbl(
	TYUMON_ID INT,--(10),
	TYUMON_PRODUCT_ID CHAR(5),
	TYUMON_KOKYAKU_ID INT,--(5),
	TYUMON_AT DATETIME,
	PRIMARY KEY(TYUMON_ID)
);

CREATE TABLE team13_admin_tbl(
	KANRI_ID CHAR(5),
	KANRI_NM VARCHAR(30) NOT NULL,
	KANRI_PASS VARCHAR2(30) NOT NULL,
	PRIMARY KEY(KANRI_ID)
);

CREATE TABLE team13_shiire_history_tbl(
	SHIIRE_HISTORY_ID CHAR(5),
	SHIIRE_KANRI_ID CHAR(5),
	SHIIRE_MAKER_ID CHAR(5),
	SHIIRE_NUM NUMBER(5),
	BOUGHT_AT DATETIME,
	PRIMARY KEY(SHIIRE_HISTORY_ID)
);

CREATE TABLE team13_shiire_tbl(
	SHIIRE_ID CHAR(5),
	SHIIRE_NM VARCHAR2(30),
	SHIIRE_PRODUCT_ID CHAR(5),
	SHIIRE_ADRESS VARCHAR2(30),
	SHIIRE_TELL VARCHAR2(20),
	PRIMARY KEY(SHIIRE_ID)
);

CREATE TABLE team13_cart_shohin_table(
	CART_SHOHIN_ID CHAR(5),
	CART_SHOHIN_NM VARCHAR2(30),
	CART_SHAIN_ID CHAR(5),
	CART_SHOHIN_NUM NUMBER(5),
	CART_SHOHIB_PRICE NUMBER(6),
	PRIMARY KEY(CART_SHOHIN_ID)
);

CREATE TABLE team13_shiharai_tbl(
	SHIHARAI_ID INT,--(2),
	SHIHARAI_NM VARCHAR2(30) NOT NULL,
	PRIMARY KEY(SHIHARAI_ID)
);

CREATE TABLE team13_card_info_tbl(
	CARD_INFO_ID CHAR(5),
	CARD_INFO_NM VARCHAR2(6),
	CARD_INFO_NUM VARCHAR2(20),
	CARD_LIMIT_TIME VARCHAR2(6),
	CARD_USER_ID INT,--(6),
	PRIMARY KEY(CARD_INFO_ID)
);



