DROP TABLE IF EXISTS BUMON_TBL;
CREATE TABLE team13_shain_tbl(
	SHAIN_ID CHAR(2),
	SHAIN_NM VARCHAR2(30),
	SHAIN_ADRESS VARCHAR(30),
	SHAIN_EMAIL VARCHAR(30),
	SHAIN_TELL VARCHAR(20),	
	PRIMARY KEY(SHAIN_ID)
	);

